### PR TITLE
Build Tasks

### PR DESCRIPTION
**Pull request by henriquesosa**
Hi, I created a Gulpfile  to optimize the building process to production.

### CODE REVIEW

**Comment by viljamis** [comment]
@henriquesosa This is amazing, thank you!!

**Comment by henriquesosa** [comment]
i only forgot to update the README file.

**Comment by henriquesosa** [comment]
@viljamis any news about this PL ?

**Comment by viljamis** [comment]
@henriquesosa Sorry for the delay! Just relocated a new country so in the middle of dozen things. But looking into this as we speak!

**Comment by viljamis** [comment]
Merged!

**Pull request merged**
